baza = [
    {
        id:'0-1',
        amount:'0-1',
        date:'0-1',
        business:'0-1',
        name:'0-1',
        type:'0-1',
        account:'0-1',
    },
    {
        id:'0-2',
        amount:'0-2',
        date:'0-2',
        business:'0-2',
        name:'0-2',
        type:'0-2',
        account:'0-2',
    },
    {
        id:'0-3',
        amount:'0-3',
        date:'0-3',
        business:'0-3',
        name:'0-3',
        type:'0-3',
        account:'0-3',
    },
    {
        id:'0-4',
        amount:'0-4',
        date:'0-4',
        business:'0-4',
        name:'0-4',
        type:'0-4',
        account:'0-4',
    },
    {
        id:'0-5',
        amount:'0-5',
        date:'0-5',
        business:'0-5',
        name:'0-5',
        type:'0-5',
        account:'0-5',
    },
    ]

// import transactionHistory from './transaction-history.js';

console.log(baza[0]);